[plugins]

[libraries]
ai-djl-api = { group = "ai.djl", name = "api", version = "0.32.0" }
ai-djl-pytorch = { group = "ai.djl.pytorch", name = "pytorch-engine", version = "0.32.0" }
metadata-extractor = { group = "com.drewnoakes", name = "metadata-extractor", version = "2.19.0" }

commons-io = { group = "commons-io", name = "commons-io", version = "2.18.0" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = "3.17.0" }
lombok = { group = "org.projectlombok", name = "lombok", version = "1.18.38" }
jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.1" }

slf4j-api= { group = "org.slf4j", name = "slf4j-api", version = "2.0.17" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.5.18" }

junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version = "5.11.4" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.11.4" }
hamcrest-matchers = { group = "org.hamcrest", name = "hamcrest", version = "2.2" }
hamcrest-record = { group = "rocks.cleancode", name = "hamcrest-record", version = "1.0.0" }
